services:
  # Backend API Service
  - type: web
    name: crisisassist-backend
    env: node
    plan: free
    buildCommand: |
      npm install
      cd backend
      npm install
      npm run build
    startCommand: cd backend && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: crisisassist-db
          property: connectionString
      - key: DEMO_MODE
        value: true
      - key: LOG_TO_FILE
        value: false
      - key: CORS_ORIGIN
        value: "*"
        
  # Frontend Web App
  - type: web
    name: crisisassist-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://crisisassist-backend.onrender.com
      - key: NODE_ENV
        value: production
        
databases:
  - name: crisisassist-db
    databaseName: crisisassist
    user: crisisassist_user
    plan: free
